"""html_report.py — single-file HTML report with equity curve, underwater DD, metrics table."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np


_TEMPLATE = r"""<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>{title}</title>
<style>
body{{background:#0a0d12;color:#e6edf3;font-family:'Segoe UI',sans-serif;margin:0;padding:30px;}}
h1{{font-size:28px;letter-spacing:-.5px;margin-bottom:6px;}}
h1 span{{background:linear-gradient(110deg,#e8b949,#f3d488);-webkit-background-clip:text;color:transparent;}}
.sub{{color:#7c828e;margin-bottom:28px;}}
.kpi{{display:grid;grid-template-columns:repeat(6,1fr);gap:14px;margin-bottom:22px;}}
.kpi div{{background:#141a24;border:1px solid #232a36;border-radius:11px;padding:16px;text-align:center;}}
.kpi .v{{font-size:23px;font-weight:800;letter-spacing:-.4px;font-family:Consolas,monospace;}}
.kpi .l{{font-size:11px;color:#7c828e;letter-spacing:1px;text-transform:uppercase;margin-top:5px;}}
.panel{{background:#141a24;border:1px solid #232a36;border-radius:14px;padding:22px;margin-bottom:18px;}}
.green{{color:#4ec77f;}} .red{{color:#ef5b54;}} .gold{{color:#e8b949;}}
canvas{{width:100%;height:460px;display:block;border-radius:8px;}}
.chart-shell{{position:relative;}}
.chart-stats{{position:absolute;top:14px;right:18px;display:flex;gap:18px;background:rgba(15,20,28,.85);
padding:10px 18px;border-radius:10px;border:1px solid #2a3240;backdrop-filter:blur(8px);z-index:2;}}
.chart-stats div{{text-align:right;}}
.chart-stats .lbl{{font-size:10px;color:#7c828e;text-transform:uppercase;letter-spacing:1px;}}
.chart-stats .val{{font-size:18px;font-weight:800;font-family:Consolas,monospace;letter-spacing:-.3px;}}
.chart-stats .green{{color:#3df58c;}} .chart-stats .red{{color:#ff5a52;}}
table{{width:100%;border-collapse:collapse;font-size:13px;}}
th,td{{padding:9px 11px;text-align:left;border-bottom:1px solid #232a36;}}
th{{color:#7c828e;text-transform:uppercase;font-size:11px;letter-spacing:.5px;}}
.foot{{color:#7c828e;font-size:12px;margin-top:18px;text-align:center;}}
</style></head><body>
<h1>{title} <span>{symbol}</span></h1>
<div class="sub">{period} &middot; {bars} bars &middot; {trades_n} trades &middot; generated by quant-lab</div>

<div class="kpi">
  <div><div class="v {profit_class}">${net_profit}</div><div class="l">Net Profit</div></div>
  <div><div class="v">{return_pct}%</div><div class="l">Return</div></div>
  <div><div class="v">{pf}</div><div class="l">Profit Factor</div></div>
  <div><div class="v">{win_rate}%</div><div class="l">Win Rate</div></div>
  <div><div class="v green">{max_dd_pct}%</div><div class="l">Max DD</div></div>
  <div><div class="v">{sharpe}</div><div class="l">Sharpe</div></div>
</div>

<div class="panel">
  <h3 style="margin-bottom:14px;">Equity Curve &amp; Drawdown</h3>
  <div class="chart-shell">
    <div class="chart-stats">
      <div><div class="lbl">Return</div><div class="val {profit_class}">{return_pct}%</div></div>
      <div><div class="lbl">Net P/L</div><div class="val {profit_class}">${net_profit}</div></div>
      <div><div class="lbl">Max DD</div><div class="val">{max_dd_pct}%</div></div>
      <div><div class="lbl">Trades</div><div class="val">{trades_n}</div></div>
    </div>
    <canvas id="ec"></canvas>
  </div>
</div>

<div class="panel">
  <h3 style="margin-bottom:8px;">All Metrics</h3>
  <table>{rows}</table>
</div>

{mc_panel}
{wf_panel}
{regime_panel}

<div class="foot">quant-lab autonomous validation pipeline</div>

<script>
const EQ={equity_js};
const cv=document.getElementById('ec');
let _progress=0;
function draw(p){{
  const dpr=window.devicePixelRatio||1;
  const W=cv.clientWidth,H=cv.clientHeight;cv.width=W*dpr;cv.height=H*dpr;
  const ctx=cv.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,W,H);
  const padL=70,padR=22,padT=22,padB=46;
  const eqH=(H-padT-padB)*0.72,ddGap=18;
  const ddTop=padT+eqH+ddGap,ddH=(H-padB)-ddTop;
  const n=EQ.length;
  const lo=Math.min.apply(null,EQ),hi=Math.max.apply(null,EQ);
  const pad=(hi-lo)*0.08,yLo=lo-pad,yHi=hi+pad;
  const START=EQ[0];
  let peakI=0,troughI=0,_mddI=0,_curPk=EQ[0],_mxd=0;
  for(let i=0;i<n;i++){{
    if(EQ[i]===hi)peakI=i; if(EQ[i]===lo)troughI=i;
    if(EQ[i]>_curPk)_curPk=EQ[i];
    const d=(_curPk-EQ[i])/_curPk; if(d>_mxd){{_mxd=d;_mddI=i;}}
  }}
  const xAt=i=>padL+(W-padL-padR)*(i/(n-1));
  const yEq=v=>padT+eqH-(v-yLo)/(yHi-yLo)*eqH;
  let pk=EQ[0],dd=[],maxdd=0;
  for(const b of EQ){{if(b>pk)pk=b;const d=(pk-b)/pk*100;dd.push(d);if(d>maxdd)maxdd=d;}}
  const ddScale=Math.max(maxdd,0.5)*1.2;
  const yDd=v=>ddTop+(v/ddScale)*ddH;
  const last=Math.max(2,Math.floor(n*p));
  // grid
  ctx.font='11px -apple-system,Segoe UI,sans-serif';ctx.fillStyle='#5b6270';ctx.textAlign='right';
  ctx.strokeStyle='rgba(255,255,255,.04)';ctx.lineWidth=1;
  for(let g=0;g<=4;g++){{
    const val=yLo+(yHi-yLo)*(1-g/4),yy=padT+eqH*g/4;
    ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(W-padR,yy);ctx.stroke();
    ctx.fillText('$'+Math.round(val).toLocaleString(),padL-8,yy+4);
  }}
  // equity area — modern gradient
  const greenColor='#3df58c',redColor='#ff5a52';
  const isProfit=EQ[last-1]>=START;
  const mainColor=isProfit?greenColor:redColor;
  const grA=ctx.createLinearGradient(0,padT,0,padT+eqH);
  grA.addColorStop(0,isProfit?'rgba(61,245,140,.42)':'rgba(255,90,82,.42)');
  grA.addColorStop(0.5,isProfit?'rgba(61,245,140,.15)':'rgba(255,90,82,.15)');
  grA.addColorStop(1,'rgba(61,245,140,0)');
  ctx.beginPath();ctx.moveTo(xAt(0),padT+eqH);ctx.lineTo(xAt(0),yEq(EQ[0]));
  for(let i=1;i<last;i++)ctx.lineTo(xAt(i),yEq(EQ[i]));
  ctx.lineTo(xAt(last-1),padT+eqH);ctx.closePath();ctx.fillStyle=grA;ctx.fill();
  // start reference dashed
  ctx.setLineDash([5,5]);ctx.strokeStyle='rgba(255,255,255,.15)';ctx.lineWidth=1;
  ctx.beginPath();ctx.moveTo(padL,yEq(START));ctx.lineTo(W-padR,yEq(START));ctx.stroke();ctx.setLineDash([]);
  ctx.font='10px Consolas';ctx.fillStyle='#5b6270';ctx.textAlign='left';
  ctx.fillText('start $'+Math.round(START).toLocaleString(),padL+6,yEq(START)-4);
  // equity line with glow
  ctx.shadowColor=mainColor;ctx.shadowBlur=12;
  ctx.strokeStyle=mainColor;ctx.lineWidth=2.4;ctx.lineCap='round';ctx.lineJoin='round';
  ctx.beginPath();ctx.moveTo(xAt(0),yEq(EQ[0]));
  for(let i=1;i<last;i++)ctx.lineTo(xAt(i),yEq(EQ[i]));ctx.stroke();
  ctx.shadowBlur=0;
  // head dot
  const curX=xAt(last-1),curY=yEq(EQ[last-1]);
  ctx.fillStyle=mainColor;ctx.beginPath();ctx.arc(curX,curY,4.5,0,Math.PI*2);ctx.fill();
  ctx.strokeStyle='rgba(255,255,255,.4)';ctx.lineWidth=1.5;
  ctx.beginPath();ctx.arc(curX,curY,8,0,Math.PI*2);ctx.stroke();
  // peak and trough callouts after animation
  if(p>=0.95){{
    const pX=xAt(peakI),pY=yEq(hi);
    ctx.fillStyle=greenColor;ctx.beginPath();ctx.arc(pX,pY,3.5,0,Math.PI*2);ctx.fill();
    ctx.fillStyle='rgba(61,245,140,.95)';ctx.font='bold 11px -apple-system,Segoe UI,sans-serif';
    ctx.textAlign=pX>W*0.7?'right':'left';
    ctx.fillText('PEAK $'+Math.round(hi).toLocaleString(),pX>W*0.7?pX-8:pX+8,pY-8);
    const tX=xAt(_mddI),tY=yEq(EQ[_mddI]);
    ctx.fillStyle=redColor;ctx.beginPath();ctx.arc(tX,tY,3.5,0,Math.PI*2);ctx.fill();
    ctx.fillStyle='rgba(255,90,82,.9)';ctx.font='11px -apple-system,Segoe UI,sans-serif';
    ctx.textAlign=tX>W*0.7?'right':'left';
    ctx.fillText('worst DD -'+maxdd.toFixed(1)+'%',tX>W*0.7?tX-8:tX+8,tY+16);
  }}
  // drawdown panel
  ctx.font='10px Consolas';ctx.fillStyle='#5b6270';ctx.textAlign='right';
  ctx.strokeStyle='rgba(255,255,255,.05)';
  ctx.beginPath();ctx.moveTo(padL,ddTop);ctx.lineTo(W-padR,ddTop);ctx.stroke();
  ctx.fillText('0%',padL-8,ddTop+4);
  ctx.fillText('-'+ddScale.toFixed(1)+'%',padL-8,ddTop+ddH);
  const grDD=ctx.createLinearGradient(0,ddTop,0,ddTop+ddH);
  grDD.addColorStop(0,'rgba(255,90,82,0)');
  grDD.addColorStop(1,'rgba(255,90,82,.35)');
  ctx.beginPath();ctx.moveTo(xAt(0),ddTop);
  for(let i=0;i<last;i++)ctx.lineTo(xAt(i),yDd(dd[i]));
  ctx.lineTo(xAt(last-1),ddTop);ctx.closePath();ctx.fillStyle=grDD;ctx.fill();
  ctx.strokeStyle=redColor;ctx.lineWidth=1.5;
  ctx.beginPath();ctx.moveTo(xAt(0),yDd(dd[0]));
  for(let i=1;i<last;i++)ctx.lineTo(xAt(i),yDd(dd[i]));ctx.stroke();
  // x-axis trade numbers
  ctx.fillStyle='#5b6270';ctx.font='10px Consolas';ctx.textAlign='center';
  for(let i=0;i<=6;i++){{
    const idx=Math.round((n-1)*i/6),xx=xAt(idx);
    ctx.fillText('#'+idx,xx,H-padB+18);
    ctx.strokeStyle='rgba(255,255,255,.03)';
    ctx.beginPath();ctx.moveTo(xx,padT);ctx.lineTo(xx,padT+eqH);ctx.stroke();
  }}
  ctx.font='10px -apple-system,Segoe UI,sans-serif';ctx.fillText('trade #',W/2,H-padB+34);
}}
function animate(){{_progress=Math.min(1,_progress+0.022);draw(_progress);if(_progress<1)requestAnimationFrame(animate);}}
animate();
window.addEventListener('resize',()=>draw(1));
</script>
</body></html>"""


def _table_rows(metrics: dict) -> str:
    skip = {"net_profit", "return_pct", "profit_factor", "win_rate", "max_dd_pct", "sharpe"}
    rows = ""
    for k, v in metrics.items():
        if k in skip:
            continue
        rows += f"<tr><th>{k}</th><td style='text-align:right;font-family:Consolas,monospace;'>{v}</td></tr>"
    return rows


def _mc_panel(mc: dict | None) -> str:
    if not mc:
        return ""
    return f"""
<div class="panel"><h3 style="margin-bottom:8px;">Monte Carlo ({mc.get('n_runs',0)} runs, shuffled trade order)</h3>
<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;font-size:13px;">
  <div>P5 equity: <b>${mc.get('p5_equity','—')}</b></div>
  <div>Median equity: <b>${mc.get('p50_equity','—')}</b></div>
  <div>P95 equity: <b>${mc.get('p95_equity','—')}</b></div>
  <div>Prob profitable: <b>{(mc.get('prob_profitable',0)*100):.1f}%</b></div>
  <div>P5 DD: <b>{mc.get('p5_dd_pct','—')}%</b></div>
  <div>Median DD: <b>{mc.get('p50_dd_pct','—')}%</b></div>
  <div>P95 DD: <b>{mc.get('p95_dd_pct','—')}%</b></div>
  <div>Verdict: <b class="{'green' if mc.get('passed') else 'red'}">{'PASSED' if mc.get('passed') else 'FAILED'}</b></div>
</div></div>"""


def _wf_panel(wf: dict | None) -> str:
    if not wf or not wf.get("windows"):
        return ""
    rows = "<tr><th>#</th><th>OOS range</th><th>Trades</th><th>PF</th><th>Net</th><th>DD%</th></tr>"
    for w in wf["windows"]:
        m = w.get("oos_metrics") or {}
        rows += (f"<tr><td>{w['window']}</td><td>{w['oos_range'][0][:10]} → {w['oos_range'][1][:10]}</td>"
                 f"<td>{m.get('trades','—')}</td><td>{m.get('profit_factor','—')}</td>"
                 f"<td>{m.get('net_profit','—')}</td><td>{m.get('max_dd_pct','—')}</td></tr>")
    verdict = "PASSED" if wf.get("passed") else "FAILED"
    cls = "green" if wf.get("passed") else "red"
    return f"""<div class="panel"><h3 style="margin-bottom:8px;">Walk-Forward Analysis</h3>
<table>{rows}</table>
<div style="margin-top:10px;font-size:13px;">
  Profitable windows: <b>{wf.get('profitable_windows',0)} / {wf.get('n_windows',0)}</b>
  &middot; Median OOS PF: <b>{wf.get('median_oos_pf',0):.2f}</b>
  &middot; Verdict: <b class="{cls}">{verdict}</b>
</div></div>"""


def _regime_panel(rg: dict | None) -> str:
    if not rg or not rg.get("per_regime"):
        return ""
    rows = "<tr><th>Regime</th><th>Trades</th><th>Net</th><th>Win %</th><th>Profitable?</th></tr>"
    for r, m in rg["per_regime"].items():
        ok = "✓" if m.get("profitable") else "✗"
        rows += (f"<tr><td>{r}</td><td>{m.get('trades',0)}</td><td>{m.get('net',0)}</td>"
                 f"<td>{m.get('win_rate','—')}</td><td>{ok}</td></tr>")
    return f"""<div class="panel"><h3 style="margin-bottom:8px;">Regime Split</h3>
<table>{rows}</table>
<div style="margin-top:10px;font-size:13px;">Profitable in <b>{rg.get('profitable_regimes',0)}/3</b> regimes
&middot; Balanced: <b class="{'green' if rg.get('balanced') else 'red'}">{'YES' if rg.get('balanced') else 'NO'}</b></div>
</div>"""


def _data_panel(data_summary: dict | None) -> str:
    if not data_summary: return ""
    d = data_summary
    return f"""<div class="panel"><h3 style="margin-bottom:8px;">Data Used</h3>
<table>
<tr><th>Source</th><td>{d.get('source', 'primary CSV')}</td></tr>
<tr><th>Bars (rows)</th><td>{d.get('rows', '—'):,}</td></tr>
<tr><th>Date range</th><td>{d.get('range', ['—', '—'])[0]} → {d.get('range', ['—', '—'])[1]}</td></tr>
<tr><th>Resampled to</th><td>{d.get('exec_tf', '—')} ({d.get('exec_bars', '—'):,} bars after resample)</td></tr>
<tr><th>IS / OOS split</th><td>{d.get('is_pct', 70)}% / {d.get('oos_pct', 30)}% — IS {d.get('is_bars', '—'):,} bars, OOS {d.get('oos_bars', '—'):,} bars</td></tr>
<tr><th>Sessions used</th><td>{', '.join(d.get('sessions', [])) or '—'}</td></tr>
<tr><th>Data quality</th><td>{d.get('usable_pct', 100)}% usable · {d.get('duplicates', 0)} duplicates · {d.get('large_gaps_gt_72h', 0)} large gaps</td></tr>
</table></div>"""


def _candidates_panel(candidates: list | None) -> str:
    if not candidates: return ""
    rows = ("<tr><th>#</th><th>Strategy</th><th>OOS Profit</th><th>OOS PF</th>"
            "<th>OOS DD</th><th>OOS Trades</th><th>WF</th><th>MC p5</th><th>Status</th><th>Why failed</th></tr>")
    for i, c in enumerate(candidates, 1):
        oos = c.get("oos_metrics", {}) or {}
        wf = c.get("wf", {}) or {}
        mc = c.get("mc", {}) or {}
        ok = c.get("passed", False)
        status = '<span class="green">PASS</span>' if ok else '<span class="red">FAIL</span>'
        reasons = "; ".join(c.get("reasons", [])) or "—"
        rows += (f"<tr><td>{i}</td><td><b>{c.get('name', '?')}</b></td>"
                 f"<td>${oos.get('net_profit', '—')}</td>"
                 f"<td>{oos.get('profit_factor', '—')}</td>"
                 f"<td>{oos.get('max_dd_pct', '—')}%</td>"
                 f"<td>{oos.get('trades', '—')}</td>"
                 f"<td>{wf.get('profitable_windows', '—')}/{wf.get('n_windows', '—')}</td>"
                 f"<td>${mc.get('p5_equity', '—')}</td>"
                 f"<td>{status}</td>"
                 f"<td style='font-size:11px;color:#7c828e;'>{reasons}</td></tr>")
    return f"""<div class="panel"><h3 style="margin-bottom:8px;">All Candidates Evaluated ({len(candidates)})</h3>
<table>{rows}</table>
<div style="margin-top:10px;font-size:12px;color:#7c828e;">Every candidate must pass ALL gates: OOS PF&gt;1.10, WF&ge;3/5, MC p5&gt;start, OOS DD&lt;15%, OOS trades&ge;100, IS/OOS&lt;2.5x, no IS+/OOS-.</div></div>"""


def _cross_source_panel(cross: dict | None) -> str:
    if not cross: return ""
    if not cross.get("available"):
        return f"""<div class="panel"><h3 style="margin-bottom:8px;">Cross-Source Verification</h3>
<div style="font-size:13px;color:#7c828e;">Cross-source check unavailable — {cross.get('error', 'no alternate data source')}.<br>
<b style="color:#ef5b54;">Demo-forward-test on YOUR live broker is MANDATORY before risking capital.</b></div></div>"""
    m = cross.get("metrics", {}) or {}
    badge = ('<span class="green">PASSED</span>' if cross.get("passed")
             else '<span class="red">FAILED</span>')
    return f"""<div class="panel"><h3 style="margin-bottom:8px;">Cross-Source Verification ({cross.get('source','?')})</h3>
<div style="margin-bottom:8px;font-size:12px;color:#7c828e;">{cross.get('gate_used', '')}</div>
<table>
<tr><th>Metric</th><th>Primary</th><th>Cross-source ({cross.get('source','?')})</th></tr>
<tr><td>Profit factor</td><td>—</td><td>{m.get('profit_factor', '—')}</td></tr>
<tr><td>Net profit</td><td>—</td><td>${m.get('net_profit', '—')}</td></tr>
<tr><td>Max drawdown</td><td>—</td><td>{m.get('max_dd_pct', '—')}%</td></tr>
<tr><td>Trades</td><td>—</td><td>{m.get('trades', '—')} ({cross.get('bars','?')} bars)</td></tr>
<tr><td>Verdict</td><td>—</td><td>{badge}</td></tr>
</table></div>"""


def _pipeline_panel(pipeline: dict | None) -> str:
    if not pipeline: return ""
    p = pipeline
    return f"""<div class="panel"><h3 style="margin-bottom:8px;">Pipeline Configuration</h3>
<table>
<tr><th>Candidates evaluated</th><td>{p.get('n_candidates', '—')}</td></tr>
<tr><th>GA population × generations (IS)</th><td>{p.get('ga_pop_is', '—')} × {p.get('ga_gens_is', '—')} = {p.get('ga_pop_is', 0) * p.get('ga_gens_is', 0)} backtests/candidate</td></tr>
<tr><th>GA pop × gens (WF)</th><td>{p.get('ga_pop_wf', '—')} × {p.get('ga_gens_wf', '—')} × 5 windows</td></tr>
<tr><th>Walk-forward windows</th><td>{p.get('wf_windows', 5)}</td></tr>
<tr><th>Monte Carlo runs</th><td>{p.get('mc_runs', 1000)}</td></tr>
<tr><th>Auto-refine attempts</th><td>{p.get('attempt', 1)} of max 3</td></tr>
<tr><th>Refinement reason (this attempt)</th><td>{p.get('refinement_reason', '—')}</td></tr>
<tr><th>Elapsed (this attempt)</th><td>{p.get('elapsed_sec', '—')} sec</td></tr>
</table></div>"""


def write_html_report(
    out_path: str | Path,
    title: str,
    symbol: str,
    period: str,
    bars: int,
    metrics: dict,
    equity: list | np.ndarray,
    mc: dict | None = None,
    wf: dict | None = None,
    regime: dict | None = None,
    data_summary: dict | None = None,
    candidates: list | None = None,
    cross_source: dict | None = None,
    pipeline: dict | None = None,
) -> str:
    """Render the validation HTML report with all available context.
    All optional panels (data_summary, candidates, cross_source, pipeline,
    mc, wf, regime) render only when their data is provided — no empty boxes.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    profit_class = "green" if metrics.get("net_profit", 0) > 0 else "red"

    # Combine optional panels — they render in this order at the bottom
    extra_panels = (_data_panel(data_summary)
                    + _candidates_panel(candidates)
                    + _mc_panel(mc)
                    + _wf_panel(wf)
                    + _regime_panel(regime)
                    + _cross_source_panel(cross_source)
                    + _pipeline_panel(pipeline))

    html = _TEMPLATE.format(
        title=title, symbol=symbol, period=period, bars=bars,
        trades_n=metrics.get("trades", 0),
        net_profit=metrics.get("net_profit", 0),
        return_pct=metrics.get("return_pct", 0),
        pf=metrics.get("profit_factor", 0),
        win_rate=metrics.get("win_rate", 0),
        max_dd_pct=metrics.get("max_dd_pct", 0),
        sharpe=metrics.get("sharpe", 0),
        profit_class=profit_class,
        rows=_table_rows(metrics),
        mc_panel="",        # render via extra_panels instead
        wf_panel=extra_panels,
        regime_panel="",
        equity_js=json.dumps([round(float(x), 2) for x in equity]),
    )
    out_path.write_text(html, encoding="utf-8")
    return str(out_path)
