"""mq5_exporter.py — generate a minimal compilable MQL5 EA from a strategy spec.

Takes a strategy name + final tuned params + the *family* (trend / meanrev / breakout)
and writes a `.mq5` file with those values hard-coded as `const`.

The output uses stock indicators (iMA, iRSI, iATR, iADX) and CTrade — it compiles
out of the box in MetaEditor.
"""
from __future__ import annotations
from pathlib import Path


_TREND_TPL = r"""//+------------------------------------------------------------------+
//| {name}.mq5 - auto-generated by quant-lab on {date}
//| Hard-coded params from validated strategy. Compile and run on
//| {symbol} {timeframe}. Risk per trade {risk_pct}%.
//+------------------------------------------------------------------+
#property copyright "quant-lab"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>

input double InpRiskPercent = {risk_pct};
input long   InpMagicNumber = {magic};

const ENUM_TIMEFRAMES TfExec    = {tf_exec};
const ENUM_TIMEFRAMES TfConfirm = {tf_confirm};
const ENUM_TIMEFRAMES TfTrend   = {tf_trend};
const int    EmaFast     = {ema_fast};
const int    EmaSlow     = {ema_slow};
const int    RsiPeriod   = {rsi_period};
const double RsiBuy      = {rsi_buy};
const double RsiSell     = {rsi_sell};
const int    AtrPeriod   = {atr_period};
const int    AdxPeriod   = {adx_period};
const double AdxMin      = {adx_min};
const double EmaGapAtr   = {ema_gap_atr};
const double SlMult      = {atr_sl_mult};
const double TpMult      = {atr_tp_mult};

CTrade trade;
int hEmaF, hEmaS, hRsi, hAtr, hAdx;
int hEmaFc, hEmaSc, hEmaFt, hEmaSt;
datetime lastBar = 0;

int OnInit() {{
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(20);
   hEmaF  = iMA(_Symbol, TfExec,    EmaFast, 0, MODE_EMA, PRICE_CLOSE);
   hEmaS  = iMA(_Symbol, TfExec,    EmaSlow, 0, MODE_EMA, PRICE_CLOSE);
   hEmaFc = iMA(_Symbol, TfConfirm, EmaFast, 0, MODE_EMA, PRICE_CLOSE);
   hEmaSc = iMA(_Symbol, TfConfirm, EmaSlow, 0, MODE_EMA, PRICE_CLOSE);
   hEmaFt = iMA(_Symbol, TfTrend,   EmaFast, 0, MODE_EMA, PRICE_CLOSE);
   hEmaSt = iMA(_Symbol, TfTrend,   EmaSlow, 0, MODE_EMA, PRICE_CLOSE);
   hRsi   = iRSI(_Symbol, TfExec, RsiPeriod, PRICE_CLOSE);
   hAtr   = iATR(_Symbol, TfExec, AtrPeriod);
   hAdx   = iADX(_Symbol, TfExec, AdxPeriod);
   return INIT_SUCCEEDED;
}}
void OnDeinit(const int reason) {{
   IndicatorRelease(hEmaF); IndicatorRelease(hEmaS);
   IndicatorRelease(hEmaFc); IndicatorRelease(hEmaSc);
   IndicatorRelease(hEmaFt); IndicatorRelease(hEmaSt);
   IndicatorRelease(hRsi); IndicatorRelease(hAtr); IndicatorRelease(hAdx);
}}
bool one(int h, int buf, int shift, double &out) {{
   double tmp[]; if(CopyBuffer(h,buf,shift,1,tmp)!=1) return false; out=tmp[0]; return true;
}}
double calcLots(double slDistPrice) {{
   double bal = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk = bal * InpRiskPercent / 100.0;
   double askPx = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double lossOneLot = 0;
   if(!OrderCalcProfit(ORDER_TYPE_BUY, _Symbol, 1.0, askPx, askPx - slDistPrice, lossOneLot))
      return 0.01;
   double riskPerLot = MathAbs(lossOneLot);
   if(riskPerLot <= 0) return 0.01;
   double lot = risk / riskPerLot;
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(step <= 0) step = 0.01;
   lot = MathFloor(lot/step)*step;
   double minlot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   if(lot < minlot) lot = minlot;
   return NormalizeDouble(lot, 2);
}}
bool hasPos(int dir) {{
   for(int i = PositionsTotal()-1; i >= 0; i--) {{
      ulong t = PositionGetTicket(i); if(t == 0) continue;
      if(!PositionSelectByTicket(t)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;
      long type = PositionGetInteger(POSITION_TYPE);
      if(dir == 1 && type == POSITION_TYPE_BUY) return true;
      if(dir == -1 && type == POSITION_TYPE_SELL) return true;
   }}
   return false;
}}
void OnTick() {{
   datetime t = iTime(_Symbol, TfExec, 0);
   if(t == lastBar) return;
   lastBar = t;
   double f,s,fc,sc,ft,st,rs,at,ax;
   if(!one(hEmaF,0,1,f) || !one(hEmaS,0,1,s)) return;
   if(!one(hEmaFc,0,1,fc) || !one(hEmaSc,0,1,sc)) return;
   if(!one(hEmaFt,0,1,ft) || !one(hEmaSt,0,1,st)) return;
   if(!one(hRsi,0,1,rs) || !one(hAtr,0,1,at) || !one(hAdx,0,1,ax)) return;
   int trend = (ft > st) ? 1 : (ft < st ? -1 : 0); if(trend == 0) return;
   int conf  = (fc > sc) ? 1 : (fc < sc ? -1 : 0); if(conf != trend) return;
   int exec  = (f > s) ? 1 : (f < s ? -1 : 0); if(exec != trend) return;
   if(ax < AdxMin) return;
   if(MathAbs(f - s) < EmaGapAtr * at) return;
   if(trend == 1  && rs <= RsiBuy) return;
   if(trend == -1 && rs >= RsiSell) return;
   if(hasPos(trend)) return;
   double slDist = SlMult * at; double tpDist = TpMult * at;
   double px = (trend == 1) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = (trend == 1) ? (px - slDist) : (px + slDist);
   double tp = (trend == 1) ? (px + tpDist) : (px - tpDist);
   double lots = calcLots(slDist);
   if(trend == 1) trade.Buy(lots, _Symbol, 0, sl, tp, "quant-lab");
   else           trade.Sell(lots, _Symbol, 0, sl, tp, "quant-lab");
}}
"""


_TF_MAP = {
    "M1": "PERIOD_M1", "M5": "PERIOD_M5", "M15": "PERIOD_M15", "M30": "PERIOD_M30",
    "H1": "PERIOD_H1", "H4": "PERIOD_H4", "D1": "PERIOD_D1",
}


# ----------------------------- MEAN-REVERSION -----------------------------
_MEANREV_TPL = r"""//+------------------------------------------------------------------+
//| {name}.mq5 - mean-reversion EA, auto-generated by quant-lab on {date}
//| {symbol} {timeframe}. Risk per trade {risk_pct}%.
//+------------------------------------------------------------------+
#property copyright "quant-lab"
#property version   "1.00"
#property strict
#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>

input double InpRiskPercent = {risk_pct};
input long   InpMagicNumber = {magic};

const ENUM_TIMEFRAMES TfExec = {tf_exec};
const int    EmaMid       = {ema_mid};
const int    RsiPeriod    = {rsi_period};
const int    AtrPeriod    = {atr_period};
const double RsiOverbought= {rsi_overbought};
const double RsiOversold  = {rsi_oversold};
const double StretchAtr   = {stretch_atr};
const double SlMult       = {atr_sl_mult};
const double TpMult       = {atr_tp_mult};

CTrade trade;
int hEma, hRsi, hAtr;
datetime lastBar = 0;

int OnInit() {{
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(20);
   hEma = iMA (_Symbol, TfExec, EmaMid, 0, MODE_EMA, PRICE_CLOSE);
   hRsi = iRSI(_Symbol, TfExec, RsiPeriod, PRICE_CLOSE);
   hAtr = iATR(_Symbol, TfExec, AtrPeriod);
   return INIT_SUCCEEDED;
}}
void OnDeinit(const int reason) {{
   IndicatorRelease(hEma); IndicatorRelease(hRsi); IndicatorRelease(hAtr);
}}
bool one(int h, int buf, int shift, double &out) {{
   double tmp[]; if(CopyBuffer(h,buf,shift,1,tmp)!=1) return false; out=tmp[0]; return true;
}}
double calcLots(double slDistPrice) {{
   double bal = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk = bal * InpRiskPercent / 100.0;
   double askPx = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double lossOneLot = 0;
   if(!OrderCalcProfit(ORDER_TYPE_BUY, _Symbol, 1.0, askPx, askPx - slDistPrice, lossOneLot)) return 0.01;
   double riskPerLot = MathAbs(lossOneLot); if(riskPerLot <= 0) return 0.01;
   double lot = risk / riskPerLot;
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP); if(step <= 0) step = 0.01;
   lot = MathFloor(lot/step)*step;
   double minlot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN); if(lot < minlot) lot = minlot;
   return NormalizeDouble(lot, 2);
}}
bool hasPos(int dir) {{
   for(int i = PositionsTotal()-1; i >= 0; i--) {{
      ulong t = PositionGetTicket(i); if(t == 0) continue;
      if(!PositionSelectByTicket(t)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;
      long type = PositionGetInteger(POSITION_TYPE);
      if(dir == 1 && type == POSITION_TYPE_BUY) return true;
      if(dir == -1 && type == POSITION_TYPE_SELL) return true;
   }}
   return false;
}}
void OnTick() {{
   datetime t = iTime(_Symbol, TfExec, 0);
   if(t == lastBar) return;
   lastBar = t;
   double mid, rs, at;
   if(!one(hEma,0,1,mid) || !one(hRsi,0,1,rs) || !one(hAtr,0,1,at)) return;
   if(at <= 0) return;
   double close = iClose(_Symbol, TfExec, 1); if(close <= 0) return;
   double stretch = (close - mid) / at;
   // SHORT — stretched above mid AND RSI overbought
   if(stretch >= StretchAtr && rs >= RsiOverbought && !hasPos(-1)) {{
      double px = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double slDist = SlMult * at;
      double sl = px + slDist; double tp = px - TpMult * at;
      double lots = calcLots(slDist);
      trade.Sell(lots, _Symbol, 0, sl, tp, "quant-lab");
   }}
   // LONG — stretched below mid AND RSI oversold
   else if(stretch <= -StretchAtr && rs <= RsiOversold && !hasPos(1)) {{
      double px = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double slDist = SlMult * at;
      double sl = px - slDist; double tp = px + TpMult * at;
      double lots = calcLots(slDist);
      trade.Buy(lots, _Symbol, 0, sl, tp, "quant-lab");
   }}
}}
"""


# ------------------------------- BREAKOUT --------------------------------
_BREAKOUT_TPL = r"""//+------------------------------------------------------------------+
//| {name}.mq5 - Donchian breakout EA, auto-generated by quant-lab on {date}
//| {symbol} {timeframe}. Risk per trade {risk_pct}%.
//+------------------------------------------------------------------+
#property copyright "quant-lab"
#property version   "1.00"
#property strict
#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>

input double InpRiskPercent = {risk_pct};
input long   InpMagicNumber = {magic};

const ENUM_TIMEFRAMES TfExec = {tf_exec};
const int    Lookback   = {lookback};
const int    AtrPeriod  = {atr_period};
const int    AdxPeriod  = {adx_period};
const double AdxMin     = {adx_min};
const double SlMult     = {atr_sl_mult};
const double TpMult     = {atr_tp_mult};

CTrade trade;
int hAtr, hAdx;
datetime lastBar = 0;

int OnInit() {{
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(20);
   hAtr = iATR(_Symbol, TfExec, AtrPeriod);
   hAdx = iADX(_Symbol, TfExec, AdxPeriod);
   return INIT_SUCCEEDED;
}}
void OnDeinit(const int reason) {{
   IndicatorRelease(hAtr); IndicatorRelease(hAdx);
}}
bool one(int h, int buf, int shift, double &out) {{
   double tmp[]; if(CopyBuffer(h,buf,shift,1,tmp)!=1) return false; out=tmp[0]; return true;
}}
double calcLots(double slDistPrice) {{
   double bal = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk = bal * InpRiskPercent / 100.0;
   double askPx = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double lossOneLot = 0;
   if(!OrderCalcProfit(ORDER_TYPE_BUY, _Symbol, 1.0, askPx, askPx - slDistPrice, lossOneLot)) return 0.01;
   double riskPerLot = MathAbs(lossOneLot); if(riskPerLot <= 0) return 0.01;
   double lot = risk / riskPerLot;
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP); if(step <= 0) step = 0.01;
   lot = MathFloor(lot/step)*step;
   double minlot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN); if(lot < minlot) lot = minlot;
   return NormalizeDouble(lot, 2);
}}
bool hasPos(int dir) {{
   for(int i = PositionsTotal()-1; i >= 0; i--) {{
      ulong t = PositionGetTicket(i); if(t == 0) continue;
      if(!PositionSelectByTicket(t)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;
      long type = PositionGetInteger(POSITION_TYPE);
      if(dir == 1 && type == POSITION_TYPE_BUY) return true;
      if(dir == -1 && type == POSITION_TYPE_SELL) return true;
   }}
   return false;
}}
void OnTick() {{
   datetime t = iTime(_Symbol, TfExec, 0);
   if(t == lastBar) return;
   lastBar = t;
   double at, ax;
   if(!one(hAtr,0,1,at) || !one(hAdx,0,1,ax)) return;
   if(at <= 0 || ax < AdxMin) return;
   // shift=1 so we never look at the still-forming current bar
   int hi_idx = iHighest(_Symbol, TfExec, MODE_HIGH, Lookback, 1);
   int lo_idx = iLowest (_Symbol, TfExec, MODE_LOW,  Lookback, 1);
   if(hi_idx < 0 || lo_idx < 0) return;
   double hh = iHigh(_Symbol, TfExec, hi_idx);
   double ll = iLow (_Symbol, TfExec, lo_idx);
   double close = iClose(_Symbol, TfExec, 1); if(close <= 0) return;
   // LONG breakout
   if(close > hh && !hasPos(1)) {{
      double px = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double slDist = SlMult * at;
      double sl = px - slDist; double tp = px + TpMult * at;
      trade.Buy(calcLots(slDist), _Symbol, 0, sl, tp, "quant-lab");
   }}
   // SHORT breakout
   else if(close < ll && !hasPos(-1)) {{
      double px = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double slDist = SlMult * at;
      double sl = px + slDist; double tp = px - TpMult * at;
      trade.Sell(calcLots(slDist), _Symbol, 0, sl, tp, "quant-lab");
   }}
}}
"""


def export_mq5(
    out_path: str | Path,
    name: str,
    symbol: str,
    timeframe: str,
    params: dict,
    family: str = "trend",
    magic: int = 246813579,
) -> str:
    """Render a compilable .mq5 file for the given strategy family.
    Supported: 'trend', 'meanrev', 'breakout'. Raises ValueError otherwise.
    """
    from datetime import date
    out_path = Path(out_path); out_path.parent.mkdir(parents=True, exist_ok=True)
    p = params

    if family == "trend":
        src = _TREND_TPL.format(
            name=name, date=date.today().isoformat(), symbol=symbol, timeframe=timeframe,
            magic=magic, risk_pct=p.get("risk_pct", 0.5),
            tf_exec=_TF_MAP[timeframe], tf_confirm=_TF_MAP.get("H1", "PERIOD_H1"),
            tf_trend=_TF_MAP.get("H4", "PERIOD_H4"),
            ema_fast=int(p.get("ema_fast", 50)), ema_slow=int(p.get("ema_slow", 200)),
            rsi_period=int(p.get("rsi_period", 14)),
            rsi_buy=p.get("rsi_buy_above", 52.0), rsi_sell=p.get("rsi_sell_below", 48.0),
            atr_period=int(p.get("atr_period", 14)), adx_period=int(p.get("adx_period", 14)),
            adx_min=p.get("adx_min", 35.0), ema_gap_atr=p.get("ema_gap_atr", 1.0),
            atr_sl_mult=p.get("atr_sl_mult", 2.0), atr_tp_mult=p.get("atr_tp_mult", 4.0),
        )

    elif family == "meanrev":
        src = _MEANREV_TPL.format(
            name=name, date=date.today().isoformat(), symbol=symbol, timeframe=timeframe,
            magic=magic, risk_pct=p.get("risk_pct", 0.5),
            tf_exec=_TF_MAP[timeframe],
            ema_mid=int(p.get("ema_mid", 50)),
            rsi_period=int(p.get("rsi_period", 14)),
            atr_period=int(p.get("atr_period", 14)),
            rsi_overbought=p.get("rsi_overbought", 72.0),
            rsi_oversold=p.get("rsi_oversold", 28.0),
            stretch_atr=p.get("stretch_atr", 1.5),
            atr_sl_mult=p.get("atr_sl_mult", 1.5), atr_tp_mult=p.get("atr_tp_mult", 1.5),
        )

    elif family == "breakout":
        src = _BREAKOUT_TPL.format(
            name=name, date=date.today().isoformat(), symbol=symbol, timeframe=timeframe,
            magic=magic, risk_pct=p.get("risk_pct", 0.5),
            tf_exec=_TF_MAP[timeframe],
            lookback=int(p.get("lookback", 20)),
            atr_period=int(p.get("atr_period", 14)),
            adx_period=int(p.get("adx_period", 14)),
            adx_min=p.get("adx_min", 25.0),
            atr_sl_mult=p.get("atr_sl_mult", 1.5), atr_tp_mult=p.get("atr_tp_mult", 3.0),
        )

    else:
        raise ValueError(f"unknown strategy family '{family}' — supported: trend, meanrev, breakout")

    out_path.write_text(src, encoding="utf-8")
    return str(out_path)
