"""pine_exporter.py — generate a TradingView PineScript v6 strategy from a
quant-lab strategy spec. Mirrors the logic of the matching MQL5 export.

Output is a `.pine` text file that the user pastes into TradingView's Pine
editor (Pine v6). The Pine version is mainly for visual inspection and a
second-opinion backtest on TradingView's data — production execution should
still use the MQL5 EA.
"""
from __future__ import annotations
from pathlib import Path
from datetime import date


_HEADER = """//@version=6
// {name} — auto-generated by quant-lab on {date}
// Symbol: {symbol} · Timeframe: {timeframe} · Risk per trade: {risk_pct}%
// PASTE into TradingView Pine editor, set chart to {timeframe} on {symbol}.
strategy("{name} (quant-lab)", overlay=true, initial_capital=10000,
         pyramiding=0,
         commission_type=strategy.commission.cash_per_contract,
         commission_value=7, slippage=10,
         default_qty_type=strategy.cash, default_qty_value=10)

riskPct = input.float({risk_pct}, "Risk % per trade", minval=0.05, step=0.05)
"""

_FOOTER_SIZING = """
// --- risk-based position sizing (in cash; TradingView scales by contract value) ---
riskCash = strategy.equity * riskPct / 100.0
qty = slDist > 0 ? math.max(1.0, riskCash / slDist) : 1.0
"""


# ----------------------------- TREND --------------------------------------
_TREND_TPL = _HEADER + r"""
// === LOCKED params from quant-lab optimisation ===
EmaFast  = {ema_fast}
EmaSlow  = {ema_slow}
RsiPer   = {rsi_period}
RsiBuy   = {rsi_buy}
RsiSell  = {rsi_sell}
AtrPer   = {atr_period}
AdxPer   = {adx_period}
AdxMin   = {adx_min}
EmaGap   = {ema_gap_atr}
SlMult   = {atr_sl_mult}
TpMult   = {atr_tp_mult}

// === execution-TF indicators ===
emaF = ta.ema(close, EmaFast)
emaS = ta.ema(close, EmaSlow)
rsiV = ta.rsi(close, RsiPer)
atrV = ta.atr(AtrPer)
[_diP, _diM, adxV] = ta.dmi(AdxPer, AdxPer)

// === higher-TF EMAs via request.security ===
[emaFc, emaSc] = request.security(syminfo.tickerid, "60",
                                  [ta.ema(close, EmaFast), ta.ema(close, EmaSlow)],
                                  lookahead=barmerge.lookahead_off)
[emaFt, emaSt] = request.security(syminfo.tickerid, "240",
                                  [ta.ema(close, EmaFast), ta.ema(close, EmaSlow)],
                                  lookahead=barmerge.lookahead_off)

trendDir = emaFt > emaSt ?  1 : emaFt < emaSt ? -1 : 0
confDir  = emaFc > emaSc ?  1 : emaFc < emaSc ? -1 : 0
execDir  = emaF  > emaS  ?  1 : emaF  < emaS  ? -1 : 0
emaGapOK = math.abs(emaF - emaS) >= EmaGap * atrV
adxOK    = adxV >= AdxMin

longSig  = trendDir ==  1 and confDir ==  1 and execDir ==  1 and rsiV > RsiBuy  and emaGapOK and adxOK
shortSig = trendDir == -1 and confDir == -1 and execDir == -1 and rsiV < RsiSell and emaGapOK and adxOK

slDist = SlMult * atrV
tpDist = TpMult * atrV
""" + _FOOTER_SIZING + """
if longSig and strategy.position_size <= 0
    strategy.entry("L", strategy.long, qty=qty)
    strategy.exit("Lx", "L", stop=close - slDist, limit=close + tpDist)

if shortSig and strategy.position_size >= 0
    strategy.entry("S", strategy.short, qty=qty)
    strategy.exit("Sx", "S", stop=close + slDist, limit=close - tpDist)
"""


# --------------------------- MEAN-REVERSION -------------------------------
_MEANREV_TPL = _HEADER + r"""
EmaMid       = {ema_mid}
RsiPer       = {rsi_period}
AtrPer       = {atr_period}
RsiOver      = {rsi_overbought}
RsiUnder     = {rsi_oversold}
StretchAtr   = {stretch_atr}
SlMult       = {atr_sl_mult}
TpMult       = {atr_tp_mult}

mid     = ta.ema(close, EmaMid)
rsiV    = ta.rsi(close, RsiPer)
atrV    = ta.atr(AtrPer)
stretch = (close - mid) / atrV
slDist  = SlMult * atrV
tpDist  = TpMult * atrV
""" + _FOOTER_SIZING + """
// SHORT — stretched above mid + RSI overbought
if stretch >= StretchAtr and rsiV >= RsiOver and strategy.position_size >= 0
    strategy.entry("S", strategy.short, qty=qty)
    strategy.exit("Sx", "S", stop=close + slDist, limit=close - tpDist)

// LONG — stretched below mid + RSI oversold
if stretch <= -StretchAtr and rsiV <= RsiUnder and strategy.position_size <= 0
    strategy.entry("L", strategy.long, qty=qty)
    strategy.exit("Lx", "L", stop=close - slDist, limit=close + tpDist)
"""


# ------------------------------- BREAKOUT ---------------------------------
_BREAKOUT_TPL = _HEADER + r"""
Lookback = {lookback}
AtrPer   = {atr_period}
AdxPer   = {adx_period}
AdxMin   = {adx_min}
SlMult   = {atr_sl_mult}
TpMult   = {atr_tp_mult}

// shift by 1 to avoid look-ahead (today's high not included in lookback)
hh = ta.highest(high, Lookback)[1]
ll = ta.lowest(low,  Lookback)[1]
atrV = ta.atr(AtrPer)
[_diP, _diM, adxV] = ta.dmi(AdxPer, AdxPer)

slDist = SlMult * atrV
tpDist = TpMult * atrV
""" + _FOOTER_SIZING + """
if close > hh and adxV >= AdxMin and strategy.position_size <= 0
    strategy.entry("L", strategy.long, qty=qty)
    strategy.exit("Lx", "L", stop=close - slDist, limit=close + tpDist)

if close < ll and adxV >= AdxMin and strategy.position_size >= 0
    strategy.entry("S", strategy.short, qty=qty)
    strategy.exit("Sx", "S", stop=close + slDist, limit=close - tpDist)
"""


# ------------------------------- MOMENTUM ---------------------------------
_MOMENTUM_TPL = _HEADER + r"""
EmaFilter   = {ema_filter}
RocPer      = {roc_period}
RocThresh   = {roc_threshold}
RsiPer      = {rsi_period}
RsiStrength = {rsi_strength}
AtrPer      = {atr_period}
SlMult      = {atr_sl_mult}
TpMult      = {atr_tp_mult}

emaF = ta.ema(close, EmaFilter)
rsiV = ta.rsi(close, RsiPer)
atrV = ta.atr(AtrPer)
roc  = (close / close[RocPer] - 1.0) * 100.0

slDist = SlMult * atrV
tpDist = TpMult * atrV
""" + _FOOTER_SIZING + """
longSig  = roc >=  RocThresh and close > emaF and rsiV >= RsiStrength
shortSig = roc <= -RocThresh and close < emaF and rsiV <= (100.0 - RsiStrength)

if longSig and strategy.position_size <= 0
    strategy.entry("L", strategy.long, qty=qty)
    strategy.exit("Lx", "L", stop=close - slDist, limit=close + tpDist)

if shortSig and strategy.position_size >= 0
    strategy.entry("S", strategy.short, qty=qty)
    strategy.exit("Sx", "S", stop=close + slDist, limit=close - tpDist)
"""


# -------------------------------- PULLBACK --------------------------------
_PULLBACK_TPL = _HEADER + r"""
EmaTrend       = {ema_trend}
EmaLong        = {ema_long}
RsiPer         = {rsi_period}
RsiPullbackMax = {rsi_pullback_max}
RsiPullbackMin = {rsi_pullback_min}
MaxDistAtr     = {max_dist_atr}
AtrPer         = {atr_period}
SlMult         = {atr_sl_mult}
TpMult         = {atr_tp_mult}

emaT = ta.ema(close, EmaTrend)
emaL = ta.ema(close, EmaLong)
rsiV = ta.rsi(close, RsiPer)
atrV = ta.atr(AtrPer)
dist = math.abs(close - emaT) / atrV

slDist = SlMult * atrV
tpDist = TpMult * atrV
""" + _FOOTER_SIZING + """
// UPTREND pullback long
if close > emaL and emaT > emaL and rsiV <= RsiPullbackMax and dist <= MaxDistAtr and strategy.position_size <= 0
    strategy.entry("L", strategy.long, qty=qty)
    strategy.exit("Lx", "L", stop=close - slDist, limit=close + tpDist)

// DOWNTREND pullback short
if close < emaL and emaT < emaL and rsiV >= RsiPullbackMin and dist <= MaxDistAtr and strategy.position_size >= 0
    strategy.entry("S", strategy.short, qty=qty)
    strategy.exit("Sx", "S", stop=close + slDist, limit=close - tpDist)
"""


# ----------------------------- dispatch -----------------------------------
def export_pine(
    out_path: str | Path,
    name: str,
    symbol: str,
    timeframe: str,
    params: dict,
    family: str = "trend",
) -> str:
    """Render a compilable .pine file for the given strategy family.
    Supported: 'trend', 'meanrev', 'breakout', 'momentum', 'pullback'.
    """
    out_path = Path(out_path); out_path.parent.mkdir(parents=True, exist_ok=True)
    p = params
    common = dict(name=name, date=date.today().isoformat(),
                  symbol=symbol, timeframe=timeframe,
                  risk_pct=p.get("risk_pct", 0.5))

    if family == "trend":
        src = _TREND_TPL.format(
            **common,
            ema_fast=int(p.get("ema_fast", 50)), ema_slow=int(p.get("ema_slow", 200)),
            rsi_period=int(p.get("rsi_period", 14)),
            rsi_buy=p.get("rsi_buy_above", 52.0), rsi_sell=p.get("rsi_sell_below", 48.0),
            atr_period=int(p.get("atr_period", 14)), adx_period=int(p.get("adx_period", 14)),
            adx_min=p.get("adx_min", 35.0), ema_gap_atr=p.get("ema_gap_atr", 1.0),
            atr_sl_mult=p.get("atr_sl_mult", 2.0), atr_tp_mult=p.get("atr_tp_mult", 4.0),
        )

    elif family == "meanrev":
        src = _MEANREV_TPL.format(
            **common,
            ema_mid=int(p.get("ema_mid", 50)),
            rsi_period=int(p.get("rsi_period", 14)),
            atr_period=int(p.get("atr_period", 14)),
            rsi_overbought=p.get("rsi_overbought", 72.0),
            rsi_oversold=p.get("rsi_oversold", 28.0),
            stretch_atr=p.get("stretch_atr", 1.5),
            atr_sl_mult=p.get("atr_sl_mult", 1.5),
            atr_tp_mult=p.get("atr_tp_mult", 1.5),
        )

    elif family == "breakout":
        src = _BREAKOUT_TPL.format(
            **common,
            lookback=int(p.get("lookback", 20)),
            atr_period=int(p.get("atr_period", 14)),
            adx_period=int(p.get("adx_period", 14)),
            adx_min=p.get("adx_min", 25.0),
            atr_sl_mult=p.get("atr_sl_mult", 1.5),
            atr_tp_mult=p.get("atr_tp_mult", 3.0),
        )

    elif family == "momentum":
        src = _MOMENTUM_TPL.format(
            **common,
            ema_filter=int(p.get("ema_filter", 100)),
            roc_period=int(p.get("roc_period", 10)),
            roc_threshold=p.get("roc_threshold", 0.5),
            rsi_period=int(p.get("rsi_period", 14)),
            rsi_strength=p.get("rsi_strength", 55.0),
            atr_period=int(p.get("atr_period", 14)),
            atr_sl_mult=p.get("atr_sl_mult", 1.8),
            atr_tp_mult=p.get("atr_tp_mult", 3.0),
        )

    elif family == "pullback":
        src = _PULLBACK_TPL.format(
            **common,
            ema_trend=int(p.get("ema_trend", 50)),
            ema_long=int(p.get("ema_long", 200)),
            rsi_period=int(p.get("rsi_period", 14)),
            rsi_pullback_max=p.get("rsi_pullback_max", 55.0),
            rsi_pullback_min=p.get("rsi_pullback_min", 45.0),
            max_dist_atr=p.get("max_dist_atr", 0.5),
            atr_period=int(p.get("atr_period", 14)),
            atr_sl_mult=p.get("atr_sl_mult", 1.5),
            atr_tp_mult=p.get("atr_tp_mult", 3.0),
        )

    else:
        raise ValueError(
            f"unknown strategy family '{family}' — "
            "supported: trend, meanrev, breakout, momentum, pullback")

    out_path.write_text(src, encoding="utf-8")
    return str(out_path)
