"""publish.py — package a validated strategy into a clean output folder.

Creates: output/<SYMBOL>_<TF>_<STRATEGY>_<TIMESTAMP>/
   ├── README.md          how to use, what's inside, perf summary
   ├── strategy.pine      TradingView Pine v6
   ├── strategy.mq5       MT5 EA (if available for the family)
   ├── params.json        all winning parameters
   ├── report.html        interactive report (copied)
   └── report.pdf         PDF version (copied)

Single function — call after pipeline returns VALIDATED.
"""
from __future__ import annotations
from pathlib import Path
from datetime import datetime
import json
import shutil


def publish_winner(
    project_root: Path,
    symbol: str,
    timeframe: str,
    strategy_name: str,
    family: str,
    params: dict,
    metrics: dict,
    html_path: str | None = None,
    pdf_path: str | None = None,
    mq5_path: str | None = None,
    pine_path: str | None = None,
) -> str:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    out_name = f"{symbol.upper()}_{timeframe}_{strategy_name}_{stamp}"
    out = project_root / "output" / out_name
    out.mkdir(parents=True, exist_ok=True)

    # Copy in standardised names
    def _cp(src, dst_name):
        if src and Path(src).is_file():
            shutil.copy2(src, out / dst_name)
            return out / dst_name
        return None

    _cp(html_path, "report.html")
    _cp(pdf_path,  "report.pdf")
    _cp(mq5_path,  "strategy.mq5")
    _cp(pine_path, "strategy.pine")

    # params + metrics snapshot
    (out / "params.json").write_text(json.dumps({
        "symbol":     symbol, "timeframe": timeframe,
        "strategy":   strategy_name, "family": family,
        "params":     params, "metrics_oos": metrics,
        "generated":  stamp,
    }, indent=2, default=str), encoding="utf-8")

    # human README
    n = metrics
    readme = f"""# {strategy_name} — {symbol} {timeframe}

Auto-generated by quant-lab on {stamp}.

## Validated performance (out-of-sample)
| Metric | Value |
|---|---|
| Net profit ($10k account) | ${n.get('net_profit', '?')} |
| Return | {n.get('return_pct', '?')}% |
| Profit factor | {n.get('profit_factor', '?')} |
| Max drawdown | {n.get('max_dd_pct', '?')}% |
| Win rate | {n.get('win_rate', '?')}% |
| Trades | {n.get('trades', '?')} |
| Sharpe | {n.get('sharpe', '?')} |

## Files in this folder
- **strategy.pine** — TradingView PineScript v6. Open Pine Editor, paste,
  set chart to **{timeframe}** on {symbol}, "Add to chart". Session
  filter is ON by default — keep it ON to match backtest.
- **strategy.mq5** — MetaTrader 5 Expert Advisor (if generated). Compile
  in MetaEditor (F7), then drag onto a **{timeframe}** {symbol} chart.
- **report.html / report.pdf** — full backtest report with equity curve.
- **params.json** — every winning input value for reproducibility.

## How to deploy (mandatory order)
1. **Run on demo for 4-6 weeks.** Compare live spread/slippage against
   backtest. If live results trail backtest by >30%, do NOT go live.
2. **Start small.** $500-1,000 live balance at 0.5% risk per trade.
3. **Scale only after 2 months** of live results consistent with demo.

## Warning
Backtest profit does NOT guarantee live profit. Markets change; your
broker's data differs from the backtest source; slippage compounds.
Treat this as a starting point, not a finished product.
"""
    (out / "README.md").write_text(readme, encoding="utf-8")
    return str(out)
